# Generated by Django 4.2.10 on 2024-08-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
